AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  chromakey-processor

  This extracts images from green screen

Parameters:
  LambdaRoleName:
    Type: String
    Description: Name of the IAM role to create for the lambda fn
  ProcessingS3BucketName:
    Type: String
    Description: S3 bucket name for processing images
  UploadBucketObjectCreatedTopic:
    Type: String
    Description: SNS topic ARN for upload bucket object created events

Resources:
  OpenCVLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: OpenCVLayer
      Description: OpenCV layer
      ContentUri: lambda-layer/cv2-python39.zip
      CompatibleRuntimes:
        - python3.9

  ChromakeyProcessor:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Role: !Ref LambdaRoleName
      Runtime: python3.9
      Timeout: 10
      MemorySize: 3008
      Environment:
        Variables:
          HSV_LOWER: '[36, 100, 100]'
          HSV_UPPER: '[70, 255, 255]'
          OUTPUT_BUCKET_NAME: !Ref ProcessingS3BucketName
      Layers:
        - !Ref OpenCVLayer

  ChromakeyProcessorSNSTriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt ChromakeyProcessor.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 'sns.amazonaws.com'
      SourceArn: !Ref UploadBucketObjectCreatedTopic

  ChromakeyProcessorSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt ChromakeyProcessor.Arn
      Protocol: lambda
      TopicArn: !Ref UploadBucketObjectCreatedTopic
