AWSTemplateFormatVersion: "2010-09-09"
Description: Business Analytics

Parameters:
  AnalyticsBucketName:
    Description: Name of Analytics Bucket
    Type: String
    Default: theme-park-business-analytics-bucket
  DataStreamName:
    Description: Name of Data Stream
    Type: String
    Default: theme-park-data-stream

Resources:
  AnalyticsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AnalyticsBucketName}-${AWS::AccountId}"

  DataFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: FirehoseAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ""
                Effect: "Allow"
                Action:
                  - "s3:AbortMultipartUpload"
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:PutObject"
                Resource:
                  - !Sub "arn:aws:s3:::${AnalyticsBucketName}"
                  - !Sub "arn:aws:s3:::${AnalyticsBucketName}/*"
              - Sid: ""
                Effect: "Allow"
                Action:
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/kinesisfirehose/${DataStreamName}-${AWS::AccountId}:log-stream:*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${AnalyticsBucketName}:log-stream:*"

  DataFirehoseDelivery:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub "${DataStreamName}-${AWS::AccountId}"
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt AnalyticsBucket.Arn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 50
        CompressionFormat: UNCOMPRESSED
        Prefix: data/
        RoleARN: !GetAtt DataFirehoseRole.Arn
        ErrorOutputPrefix: errors/
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Sub "${AWS::StackName}-data-firehose"
          LogStreamName: !Sub "${AWS::StackName}-data-firehose"
        S3BackupMode: Disabled

Outputs:
  StreamName:
    Description: Name of Data Stream
    Value: !Ref DataStreamName
  StreamArn:
    Description: ARN of Data Stream
    Value: !GetAtt DataFirehoseDelivery.Arn