AWSTemplateFormatVersion: "2010-09-09"
Description: Business Analytics

Parameters:
  AnalyticsBucketName:
    Description: Name of Analytics Bucket
    Type: String
    Default: theme-park-business-analytics-bucket
  DataStreamName:
    Description: Name of Data Stream
    Type: String
    Default: theme-park-data-stream
  LogGroupName:
    Description: Name of Log Group
    Type: String
    Default: firehose-error-log-group
  BufferIntervalSeconds:
    Description: Buffer Interval
    Type: Number
    Default: 60
    MinValue: 60
    MaxValue: 900
  BufferSizeInMBs:
    Description: Buffer Size
    Type: Number
    Default: 5
    MinValue: 1
    MaxValue: 128

Resources:
  AnalyticsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AnalyticsBucketName}-${AWS::AccountId}"

  FirehoseCloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "${DataStreamName}-${AWS::AccountId}"

  FirehoseCloudWatchLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref FirehoseCloudWatchLogGroup
      LogStreamName: error-logs

  DataFirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: FirehoseAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: ""
                Effect: "Allow"
                Action:
                  - "s3:AbortMultipartUpload"
                  - "s3:GetBucketLocation"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:PutObject"
                Resource:
                  - !Sub "arn:aws:s3:::${AnalyticsBucketName}"
                  - !Sub "arn:aws:s3:::${AnalyticsBucketName}/*"
              - Sid: ""
                Effect: "Allow"
                Action:
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${FirehoseCloudWatchLogGroup}:*"

  FirehoseDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: !Sub "${DataStreamName}-${AWS::AccountId}"
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !GetAtt AnalyticsBucket.Arn
        BufferingHints:
          IntervalInSeconds: !Ref BufferIntervalSeconds
          SizeInMBs: !Ref BufferSizeInMBs
        CompressionFormat: UNCOMPRESSED
        Prefix: data/
        ErrorOutputPrefix: errors/
        RoleARN: !GetAtt DataFirehoseRole.Arn
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref FirehoseCloudWatchLogGroup
          LogStreamName: !Ref FirehoseCloudWatchLogStream
        S3BackupMode: Disabled

Outputs:
  StreamName:
    Description: Name of Data Stream
    Value: !Sub "${DataStreamName}-${AWS::AccountId}"
  StreamArn:
    Description: ARN of Data Stream
    Value: !GetAtt FirehoseDeliveryStream.Arn