AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  realtime-ride-times-app

  Sample SAM Template for realtime-ride-times-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  LambdaRoleName:
    Type: String
    Description: Name of the IAM role to create for the lambda fn
  SNSTopicName:
    Type: String
    Description: SNS Topic that this lambda fn will publish to

Resources:
  RealTimeRideTimesLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: theme-park-ridetimes/
      Handler: app.handler
      Runtime: nodejs14.x
      Role: !Ref LambdaRoleName
      Events:
        SNSTopicTrigger:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopicName
